variable "kubeconfig_path" {
  description = "Path to the kubeconfig generated by the Infrastructure root."
  type        = string
  default     = "../Infrastructure/kubeconfig"

  validation {
    condition     = fileexists(var.kubeconfig_path)
    error_message = "The kubeconfig file was not found. Apply the Infrastructure root first, or pass -var='kubeconfig_path=PATH' for an existing kubeconfig."
  }
}

variable "cloudflare_api_token" {
  type      = string
  sensitive = true
}

variable "cloudflare_zone" {
  type = string
}

variable "acme_email" {
  type = string
}   

variable "truenas_api_key" {
  description = "API key for the TrueNAS Kubernetes CSI user."
  type        = string
  sensitive   = true
}