variable "kubeconfig_path" {
  description = "Path to the kubeconfig generated by the Infrastructure root."
  type        = string
  default     = "../Infrastructure/kubeconfig"

  validation {
    condition     = fileexists(var.kubeconfig_path)
    error_message = "The kubeconfig file was not found. Apply the Infrastructure root first, or pass -var='kubeconfig_path=PATH' for an existing kubeconfig."
  }
}

variable "cloudflare_api_token" {
  type      = string
  sensitive = true
}

variable "cloudflare_zone" {
  type = string
}

variable "acme_email" {
  type = string
}

variable "truenas_api_key" {
  description = "API key for the TrueNAS Kubernetes CSI user."
  type        = string
  sensitive   = true
}

variable "truenas_insecure_skip_tls" {
  description = "Disable TrueNAS API TLS certificate verification. Use only for explicitly trusted self-signed certificates."
  type        = bool
  default     = false
}

variable "truenas_postrender_runtime" {
  description = "Executable used for the Helm post-renderer: bash on WSL/Linux or pwsh on native Windows."
  type        = string
  default     = "bash"

  validation {
    condition     = contains(["bash", "pwsh"], var.truenas_postrender_runtime)
    error_message = "truenas_postrender_runtime must be either bash or pwsh."
  }
}

variable "truenas_ca_bundle" {
  description = "PEM-encoded CA certificate used to validate the TrueNAS HTTPS certificate."
  type        = string
  sensitive   = true

  validation {
    condition     = trimspace(var.truenas_ca_bundle) != ""
    error_message = "truenas_ca_bundle must contain the CA certificate used to validate the TrueNAS HTTPS certificate."
  }
}