variable "kubeconfig_path" {
  description = "Path to the kubeconfig generated by the Infrastructure root."
  type        = string
  default     = "../Infrastructure/kubeconfig"

  validation {
    condition     = fileexists(var.kubeconfig_path)
    error_message = "The kubeconfig file was not found. Apply the Infrastructure root first, or pass -var='kubeconfig_path=PATH' for an existing kubeconfig."
  }
}